from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json, sys
        

if __name__ == "__main__":

    season_number = sys.argv[1]
    episode_number = sys.argv[2]
    scene_number = sys.argv[3]

    # This secure connect bundle is autogenerated when you download your SCB,
    # if yours is different update the file name below
    cloud_config = {
        'secure_connect_bundle': './python/cassandra/secure-connect-friends-cassandra-db.zip'
    }

    # This token JSON file is autogenerated when you download your token,
    # if yours is different update the file name below
    with open("./python/cassandra/transaction_db-token.json") as secrets_file:
        secrets = json.load(secrets_file)

    CLIENT_ID = secrets["clientId"]
    CLIENT_SECRET = secrets["secret"]

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    session = cluster.connect()

    # Switching to the keyspace
    session.set_keyspace('utterances')

    result = session.execute(f"select max(utterance) from utterances_by_id where season = {season_number} and episode = {episode_number} and scene = {scene_number} allow filtering;").one()
    print(result[0])
